
trigger:
- master

jobs:
- job: Ubuntu
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      sudo apt-get install -y libvulkan-dev
    displayName: "apt-get"
  - script: |
      mkdir build
      cd build
      cmake ..
    displayName: 'cmake'
  - script: |
      CORE_COUNT=$(grep processor /proc/cpuinfo | wc -l)
      echo "Will build with ${CORE_COUNT} cores."
      cd build
      make -j $CORE_COUNT
    displayName: 'build'

