
trigger:
- master

variables:
- name: UBUNTU_DEP_LIST
  value: "libvulkan-dev"

jobs:
- job: Ubuntu
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      sudo apt-get install -y ${UBUNTU_DEP_LIST}
    displayName: "download and install deps"
  - script: |
      mkdir build
      cd build
      cmake .. -DBUILD_SHARED_LIBS=ON
    displayName: 'cmake'
  - script: |
      CORE_COUNT=$(grep processor /proc/cpuinfo | wc -l)
      CORES=$((${CORE_COUNT} + 1))
      cd build
      make -j $CORE_COUNT
    displayName: "build"
